algoritmo "calculeanota"
// Função :
// Autor :
// Data : 27/06/2018
// Seção de Declarações 
var
nota1: inteiro
nota2: inteiro
nota3: inteiro
nota4: inteiro
media: real
inicio
// Seção de Comandos 
escreva ("Digite a nota 1: ")
leia (nota1)
escreva ("Digite a nota 2: ")
leia (nota2)
escreva ("Digite a nota 3: ")
leia (nota3)
escreva ("Digite a nota 4: ")
leia (nota4)
media <- (nota1 + nota2 + nota3 + nota4)/4
escreva ("A sua média é: ", media)
fimalgoritmo
