algoritmo "semnome"
// Função :
// Autor :
// Data : 27/06/2018
// Seção de Declarações 
var
nome : caracter
idade : inteiro
diferenca : inteiro
inicio
// Seção de Comandos
escreva ("Nome: ")
leia (nome)
escreva ("Idade: ")
leia (idade)
diferenca <- 18 - idade
Se (idade) >= 18 entao
Escreva ("Parabéns, você está apto(a) à servir o seu país, ",nome, " -", idade)
Senao
Escreva ("Infelizmente você terá que aguardar mais", diferenca, " anos, ",nome)
FIMSE
fimalgoritmo
